# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='codigo',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
